language: node_js

node_js:
  - "node"

script:
  - npm run lint
  - npm test -- --single-run
  - cat ./coverage/lcov/lcovonly | ./node_modules/coveralls/bin/coveralls.js

notifications:
  email: false
